name: Synthetic Ping Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'npm'
    - name: Install packages
      run: npm install
    - name: Run script
      run: 'node ./examples/ping_test_headless.js'